apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: ${namespace}
spec:
  secretName: traefik-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: traefik-cert
  dnsNames:
  - ${domain-name}
  - '*.${domain-name}'
  - '*.${namespace}.${domain-name}'
  - '*.login.${domain-name}'
