apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "elasticsearch-ingressroute"
  namespace: infrastructure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`es.infrastructure.k8s.local`) && PathPrefix(`/`)
      kind: Rule
      namespace: infrastructure
      services:
      - name: elastic-es-es-http
        port: 9200
        path: /
        passHostHeader: true
        tls:
          - secretName: traefik-cert
