apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: identity-cert
  namespace: identityserver4
spec:
  secretName: identity-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: identity-cert
  dnsNames:
  - 'login.k8s.local'
  - 'admin.login.k8s.local'
  - 'api.login.k8s.local'
