admin:
  podAnnotations:
      "consul.hashicorp.com/connect-inject": "true"
      "consul.hashicorp.com/connect-service": "identityserver4-identityserver4admin-admin"
identity:
  podAnnotations:
      "consul.hashicorp.com/connect-inject": "true"
      "consul.hashicorp.com/connect-service": "identityserver4-identityserver4admin-identity"