seed:
  defaultAdmin:
    password: Password_123
    email: your.email@gmail.com

certificates:
  certManager:
    enabled: true
    issuerRef:
      name: selfsigned-ca-issuer
      kind: ClusterIssuer

admin:
  protocol: https
  domainName: admin.login.k8s.local
  ssl:
    enabled: true
    secretName: identityserver4-cert-admin
  service:
    type: ClusterIP
    port: 443
  podAnnotations:
      "consul.hashicorp.com/connect-inject": "true"
      "consul.hashicorp.com/connect-service": "identityserver4-identityserver4admin-admin"
identity:
  protocol: https
  domainName: login.k8s.local
  ssl:
    enabled: true
    secretName: identityserver4-cert-identity
  service:
    type: ClusterIP
    port: 443
  podAnnotations:
      "consul.hashicorp.com/connect-inject": "true"
      "consul.hashicorp.com/connect-service": "identityserver4-identityserver4admin-identity"
  ingress:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: login.k8s.local
        paths:
        - path: /
          backend:
            serviceName: identityserver4-identity
            servicePort: 443
    tls:
    - secretName: traefik-cert
      hosts:
        - login.k8s.local