name: E2E Messaging

on:
  pull_request:
    paths:
      - 'src/terraform/versions-messaging.yaml'

jobs:
  call_workflow:
    uses: ./.github/workflows/e2e.yml
    with:
      install_messaging: true
