name: E2E Monitoring

on:
  pull_request:
    paths:
      - 'src/terraform/versions-monitoring.yaml'

jobs:
  call_workflow:
    uses: ./.github/workflows/e2e.yml
    with:
      install_monitoring: true
